# Generated by Django 5.1.1 on 2024-09-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modifier",
            name="update_at",
        ),
    ]
