# Generated by Django 5.1.1 on 2024-09-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofiles",
            old_name="user_id",
            new_name="user",
        ),
    ]
